// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDB-9cXLcEB_1R1ieHbHkv3f0lQgpIeqs',
    appId: '1:432366397111:web:000239d511d6d5d8634f32',
    messagingSenderId: '432366397111',
    projectId: 'kadi-45b8a',
    authDomain: 'kadi-45b8a.firebaseapp.com',
    storageBucket: 'kadi-45b8a.firebasestorage.app',
    measurementId: 'G-8MBE1JL78V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXSQs0hFy3jUHMjrlK1MIwf-rxlVKwxfY',
    appId: '1:432366397111:android:ad88ff2511e5056c634f32',
    messagingSenderId: '432366397111',
    projectId: 'kadi-45b8a',
    storageBucket: 'kadi-45b8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx8n116LcZ4tDP3CLStirOkii_FTrDBVM',
    appId: '1:432366397111:ios:4c9776c4cd5061af634f32',
    messagingSenderId: '432366397111',
    projectId: 'kadi-45b8a',
    storageBucket: 'kadi-45b8a.firebasestorage.app',
    iosBundleId: 'com.example.kadi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx8n116LcZ4tDP3CLStirOkii_FTrDBVM',
    appId: '1:432366397111:ios:4c9776c4cd5061af634f32',
    messagingSenderId: '432366397111',
    projectId: 'kadi-45b8a',
    storageBucket: 'kadi-45b8a.firebasestorage.app',
    iosBundleId: 'com.example.kadi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDB-9cXLcEB_1R1ieHbHkv3f0lQgpIeqs',
    appId: '1:432366397111:web:bec805b342e10245634f32',
    messagingSenderId: '432366397111',
    projectId: 'kadi-45b8a',
    authDomain: 'kadi-45b8a.firebaseapp.com',
    storageBucket: 'kadi-45b8a.firebasestorage.app',
    measurementId: 'G-RCXZBHE6Y2',
  );

}